/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Buffer.Buffer;
import proyecto2.Init;


/**
 *
 * @author andre
 */
public class MainWindow extends javax.swing.JFrame {
    
    Buffer buffer;

    /**
     * Creates new form MainWindow
     */
    public MainWindow(Buffer buffer) {
        initComponents();
        this.buffer=buffer;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        startSim = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tier1Swars = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        tier3Swars = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tier2Swars = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        effortSwars = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tier1StarTrek = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tier3Strek = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tier2Strek = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        effortStrek = new javax.swing.JList<>();
        winnersStrek = new javax.swing.JLabel();
        winnersSwars = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        IDswarsP = new javax.swing.JLabel();
        IDStrekP = new javax.swing.JLabel();
        ID2 = new javax.swing.JLabel();
        ID1 = new javax.swing.JLabel();
        fighterStrek = new javax.swing.JLabel();
        fighterSwars = new javax.swing.JLabel();
        stateAI = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        simSpeed = new javax.swing.JComboBox<>();
        strekCharacterImage = new javax.swing.JLabel();
        swarsPersonajeImagen = new javax.swing.JLabel();
        swarsTarjeta = new javax.swing.JLabel();
        StrekPersonajeCard = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(140, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setFont(new java.awt.Font("Bodoni MT Poster Compressed", 0, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        startSim.setBackground(new java.awt.Color(255, 0, 51));
        startSim.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        startSim.setForeground(new java.awt.Color(255, 255, 255));
        startSim.setText("Iniciar Simulacion");
        startSim.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        startSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startSimActionPerformed(evt);
            }
        });
        jPanel1.add(startSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, 280, 60));

        jLabel3.setBackground(new java.awt.Color(0, 102, 204));
        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ganadores");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 150, 40));

        jLabel4.setBackground(new java.awt.Color(0, 102, 204));
        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nivel 1");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 130, 30));

        jScrollPane4.setBorder(null);

        tier1Swars.setBackground(new java.awt.Color(0, 102, 204));
        tier1Swars.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 57, 59), 1, true));
        tier1Swars.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tier1Swars.setForeground(new java.awt.Color(255, 255, 255));
        tier1Swars.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(tier1Swars);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 150, 100));

        jScrollPane5.setBorder(null);

        tier3Swars.setBackground(new java.awt.Color(0, 102, 204));
        tier3Swars.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 57, 59), 1, true));
        tier3Swars.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tier3Swars.setForeground(new java.awt.Color(255, 255, 255));
        tier3Swars.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(tier3Swars);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 690, 150, 100));

        jLabel5.setBackground(new java.awt.Color(0, 102, 204));
        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nivel 3");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 640, 130, 30));

        jLabel6.setBackground(new java.awt.Color(0, 102, 204));
        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Nivel 2");
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 130, 30));

        jScrollPane8.setBorder(null);

        tier2Swars.setBackground(new java.awt.Color(0, 102, 204));
        tier2Swars.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 57, 59), 1, true));
        tier2Swars.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tier2Swars.setForeground(new java.awt.Color(255, 255, 255));
        tier2Swars.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(tier2Swars);

        jPanel1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 150, 100));

        jLabel8.setBackground(new java.awt.Color(0, 102, 204));
        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Refuerzo");
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 640, 130, 30));

        jScrollPane9.setBorder(null);

        effortSwars.setBackground(new java.awt.Color(0, 102, 204));
        effortSwars.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 57, 59), 1, true));
        effortSwars.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        effortSwars.setForeground(new java.awt.Color(255, 255, 255));
        effortSwars.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(effortSwars);

        jPanel1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 690, 150, 100));

        jLabel7.setBackground(new java.awt.Color(255, 153, 51));
        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Ganadores");
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 240, 140, 40));

        jLabel9.setBackground(new java.awt.Color(255, 153, 51));
        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Nivel 1");
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 470, 130, 30));

        jScrollPane7.setBorder(null);

        tier1StarTrek.setBackground(new java.awt.Color(255, 153, 51));
        tier1StarTrek.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 57, 59), 1, true));
        tier1StarTrek.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tier1StarTrek.setForeground(new java.awt.Color(255, 255, 255));
        tier1StarTrek.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(tier1StarTrek);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 520, 150, 100));

        jLabel10.setBackground(new java.awt.Color(255, 153, 51));
        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Nivel 3");
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 640, 130, 30));

        jScrollPane10.setBorder(null);

        tier3Strek.setBackground(new java.awt.Color(255, 153, 51));
        tier3Strek.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 57, 59), 1, true));
        tier3Strek.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tier3Strek.setForeground(new java.awt.Color(255, 255, 255));
        tier3Strek.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane10.setViewportView(tier3Strek);

        jPanel1.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 690, 150, 100));

        jLabel11.setBackground(new java.awt.Color(255, 153, 51));
        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Nivel 2");
        jLabel11.setOpaque(true);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 470, 130, 30));

        jScrollPane11.setBorder(null);

        tier2Strek.setBackground(new java.awt.Color(255, 153, 51));
        tier2Strek.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 57, 59), 1, true));
        tier2Strek.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tier2Strek.setForeground(new java.awt.Color(255, 255, 255));
        tier2Strek.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane11.setViewportView(tier2Strek);

        jPanel1.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 520, 150, 100));

        jLabel12.setBackground(new java.awt.Color(255, 153, 51));
        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Refuerzo");
        jLabel12.setOpaque(true);
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 640, 130, 30));

        jScrollPane12.setBorder(null);

        effortStrek.setBackground(new java.awt.Color(255, 153, 51));
        effortStrek.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 57, 59), 1, true));
        effortStrek.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        effortStrek.setForeground(new java.awt.Color(255, 255, 255));
        effortStrek.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane12.setViewportView(effortStrek);

        jPanel1.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 690, 150, 100));

        winnersStrek.setBackground(new java.awt.Color(255, 153, 51));
        winnersStrek.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        winnersStrek.setForeground(new java.awt.Color(230, 225, 197));
        winnersStrek.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winnersStrek.setText("0");
        winnersStrek.setOpaque(true);
        jPanel1.add(winnersStrek, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, 90, -1));

        winnersSwars.setBackground(new java.awt.Color(0, 102, 204));
        winnersSwars.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        winnersSwars.setForeground(new java.awt.Color(230, 225, 197));
        winnersSwars.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winnersSwars.setText("0");
        winnersSwars.setOpaque(true);
        jPanel1.add(winnersSwars, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 90, -1));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AssetsVarios/d610ebba0cc387e20ea5fdb3a0e6b376.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 120, 150));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AssetsVarios/Star-Trek-Logo.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 220, 180));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AssetsVarios/star-wars-logo-3-1.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 400, 140));

        IDswarsP.setBackground(new java.awt.Color(0, 0, 153));
        IDswarsP.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        IDswarsP.setForeground(new java.awt.Color(255, 255, 255));
        IDswarsP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDswarsP.setText("None");
        IDswarsP.setOpaque(true);
        jPanel1.add(IDswarsP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 70, 30));

        IDStrekP.setBackground(new java.awt.Color(255, 153, 51));
        IDStrekP.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        IDStrekP.setForeground(new java.awt.Color(255, 255, 255));
        IDStrekP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDStrekP.setText("None");
        IDStrekP.setOpaque(true);
        jPanel1.add(IDStrekP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 400, 60, 30));

        ID2.setBackground(new java.awt.Color(255, 153, 51));
        ID2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        ID2.setForeground(new java.awt.Color(255, 255, 255));
        ID2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ID2.setText("ID:");
        ID2.setOpaque(true);
        jPanel1.add(ID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 400, 40, 30));

        ID1.setBackground(new java.awt.Color(0, 0, 153));
        ID1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        ID1.setForeground(new java.awt.Color(255, 255, 255));
        ID1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ID1.setText("ID:");
        ID1.setOpaque(true);
        jPanel1.add(ID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 40, 30));

        fighterStrek.setBackground(new java.awt.Color(255, 153, 51));
        fighterStrek.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        fighterStrek.setForeground(new java.awt.Color(255, 255, 255));
        fighterStrek.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fighterStrek.setText("Nombre Strek");
        fighterStrek.setOpaque(true);
        jPanel1.add(fighterStrek, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 360, 180, 30));

        fighterSwars.setBackground(new java.awt.Color(0, 0, 153));
        fighterSwars.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        fighterSwars.setForeground(new java.awt.Color(255, 255, 255));
        fighterSwars.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fighterSwars.setText("Nombre Swars");
        fighterSwars.setOpaque(true);
        jPanel1.add(fighterSwars, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 190, 30));

        stateAI.setBackground(new java.awt.Color(255, 0, 51));
        stateAI.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        stateAI.setForeground(new java.awt.Color(255, 255, 255));
        stateAI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stateAI.setText("Decidiendo");
        stateAI.setOpaque(true);
        jPanel1.add(stateAI, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 240, 50));

        jLabel2.setBackground(new java.awt.Color(255, 0, 51));
        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Velocidad de Simulacion");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 680, 250, 30));

        simSpeed.setBackground(new java.awt.Color(255, 0, 51));
        simSpeed.setFont(new java.awt.Font("Barlow Condensed", 0, 18)); // NOI18N
        simSpeed.setForeground(new java.awt.Color(255, 255, 255));
        simSpeed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.25", "0.5", "1", "1.5", "2", "2.5", "3" }));
        simSpeed.setSelectedIndex(2);
        simSpeed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 57, 59)));
        simSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simSpeedActionPerformed(evt);
            }
        });
        jPanel1.add(simSpeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 720, 110, -1));

        strekCharacterImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        strekCharacterImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AssetsVarios/Star_Trek_Customizable_Card_Game_cardback.jpg"))); // NOI18N
        jPanel1.add(strekCharacterImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 50, 220, 300));

        swarsPersonajeImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        swarsPersonajeImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AssetsVarios/file.png"))); // NOI18N
        jPanel1.add(swarsPersonajeImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 220, 300));

        swarsTarjeta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        swarsTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AssetsVarios/file.png"))); // NOI18N
        jPanel1.add(swarsTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 220, 300));

        StrekPersonajeCard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StrekPersonajeCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AssetsVarios/Star_Trek_Customizable_Card_Game_cardback.jpg"))); // NOI18N
        jPanel1.add(StrekPersonajeCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 50, 220, 300));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AssetsVarios/fondo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1310, 840));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startSimActionPerformed
        Init init = new Init(this, this.buffer);
        init.init();
        this.startSim.setEnabled(false);
        
    }//GEN-LAST:event_startSimActionPerformed

    private void simSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simSpeedActionPerformed
        double newSimSpeed = Double.parseDouble(this.simSpeed.getSelectedItem().toString());
       
        this.buffer.setSimSpeed(1000/newSimSpeed);
        this.buffer.setNextSim(4000/newSimSpeed);
        this.buffer.setSimLoad(2000/newSimSpeed);
        
    }//GEN-LAST:event_simSpeedActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID1;
    private javax.swing.JLabel ID2;
    private javax.swing.JLabel IDStrekP;
    private javax.swing.JLabel IDswarsP;
    private javax.swing.JLabel StrekPersonajeCard;
    private javax.swing.JList<String> effortStrek;
    private javax.swing.JList<String> effortSwars;
    private javax.swing.JLabel fighterStrek;
    private javax.swing.JLabel fighterSwars;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JComboBox<String> simSpeed;
    private javax.swing.JButton startSim;
    private javax.swing.JLabel stateAI;
    private javax.swing.JLabel strekCharacterImage;
    private javax.swing.JLabel swarsPersonajeImagen;
    private javax.swing.JLabel swarsTarjeta;
    private javax.swing.JList<String> tier1StarTrek;
    private javax.swing.JList<String> tier1Swars;
    private javax.swing.JList<String> tier2Strek;
    private javax.swing.JList<String> tier2Swars;
    private javax.swing.JList<String> tier3Strek;
    private javax.swing.JList<String> tier3Swars;
    private javax.swing.JLabel winnersStrek;
    private javax.swing.JLabel winnersSwars;
    // End of variables declaration//GEN-END:variables

   


    public javax.swing.JLabel getStrekPersonajeCard() {
        return StrekPersonajeCard;
    }

 
    public void setStrekPersonajeCard(javax.swing.JLabel StrekPersonajeCard) {
        this.StrekPersonajeCard = StrekPersonajeCard;
    }

 
    public javax.swing.JLabel getStrekPersonajeImagen() {
        return strekCharacterImage;
    }

  
    public void setStrekPersonajeImagen(javax.swing.JLabel strekCharacterImage) {
        this.strekCharacterImage = strekCharacterImage;
    }


    public javax.swing.JList<String> getEffortStrek() {
        return effortStrek;
    }


    public void setEffortStrek(javax.swing.JList<String> effortStrek) {
        this.effortStrek = effortStrek;
    }


    public javax.swing.JList<String> getEffortSwars() {
        return effortSwars;
    }


    public void setEffortSwars(javax.swing.JList<String> effortSwars) {
        this.effortSwars = effortSwars;
    }


    public javax.swing.JLabel getFighterStrek() {
        return fighterStrek;
    }

    public void setFighterStrek(javax.swing.JLabel fighterStrek) {
        this.fighterStrek = fighterStrek;
    }

 
    public javax.swing.JLabel getFighterSwars() {
        return fighterSwars;
    }

    public void setFighterSwars(javax.swing.JLabel fighterSwars) {
        this.fighterSwars = fighterSwars;
    }

    public javax.swing.JComboBox<String> getjComboBox1() {
        return simSpeed;
    }


    public javax.swing.JLabel getSwarsTarjeta() {
        return swarsTarjeta;
    }

    public void setSwarsTarjeta(javax.swing.JLabel swarsTarjeta) {
        this.swarsTarjeta = swarsTarjeta;
    }

    public javax.swing.JLabel getSwarsPersonajeImagen() {
        return swarsPersonajeImagen;
    }


    public void setSwarsPersonajeImagen(javax.swing.JLabel swarsPersonajeImagen) {
        this.swarsPersonajeImagen = swarsPersonajeImagen;
    }

    public javax.swing.JLabel getStateAI() {
        return stateAI;
    }

    public void setStateAI(javax.swing.JLabel stateAI) {
        this.stateAI = stateAI;
    }


    public javax.swing.JList<String> getTier1StarTrek() {
        return tier1StarTrek;
    }

 
    public void setTier1StarTrek(javax.swing.JList<String> tier1StarTrek) {
        this.tier1StarTrek = tier1StarTrek;
    }

    
    public javax.swing.JList<String> getTier1Swars() {
        return tier1Swars;
    }

   
    public void setTier1Swars(javax.swing.JList<String> tier1Swars) {
        this.tier1Swars = tier1Swars;
    }

    
    public javax.swing.JList<String> getTier2Strek() {
        return tier2Strek;
    }

    
    public void setTier2Strek(javax.swing.JList<String> tier2Strek) {
        this.tier2Strek = tier2Strek;
    }

   
    public javax.swing.JList<String> getTier2Swars() {
        return tier2Swars;
    }

    
    public void setTier2Swars(javax.swing.JList<String> tier2Swars) {
        this.tier2Swars = tier2Swars;
    }

    public javax.swing.JList<String> getTier3Strek() {
        return tier3Strek;
    }

    
    public void setTier3Strek(javax.swing.JList<String> tier3Strek) {
        this.tier3Strek = tier3Strek;
    }

    
    public javax.swing.JList<String> getTier3Swars() {
        return tier3Swars;
    }

    
    public void setTier3Swars(javax.swing.JList<String> tier3Swars) {
        this.tier3Swars = tier3Swars;
    }

    
    public javax.swing.JLabel getWinnersStrek() {
        return winnersStrek;
    }

    
    public void setWinnersStrek(javax.swing.JLabel winnersStrek) {
        this.winnersStrek = winnersStrek;
    }

 
    public javax.swing.JLabel getWinnersSwars() {
        return winnersSwars;
    }


    public void setWinnersSwars(javax.swing.JLabel winnersSwars) {
        this.winnersSwars = winnersSwars;
    }


    public javax.swing.JLabel getIDSwarsP() {
        return IDswarsP;
    }


    public javax.swing.JLabel getIDStrekP() {
        return IDStrekP;
    }
}
