/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Buffer.Buffer;
import proyecto2.Init;

/**
 *
 * @author andre
 */
public class MainWindow extends javax.swing.JFrame {
    
    Buffer buffer;

    /**
     * Creates new form MainWindow
     */
    public MainWindow(Buffer buffer) {
        initComponents();
        this.buffer=buffer;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        startSim = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tier1Swars = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        tier3Nick = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tier2Swars = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        effortSwars = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tier1StarTrek = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tier3Strek = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tier2Strek = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        effortStrek = new javax.swing.JList<>();
        winnersStrek = new javax.swing.JLabel();
        IDswarsP = new javax.swing.JLabel();
        IDStrekP = new javax.swing.JLabel();
        winnersSwars = new javax.swing.JLabel();
        IDcartoonText = new javax.swing.JLabel();
        IDtextNick = new javax.swing.JLabel();
        fighterStrek = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fighterSwars = new javax.swing.JLabel();
        stateAI = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        simSpeed = new javax.swing.JComboBox<>();
        strekCharacterImage = new javax.swing.JLabel();
        swarsPersonajeImagen = new javax.swing.JLabel();
        swarsTarjeta = new javax.swing.JLabel();
        StrekPersonajeCard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(140, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(230, 225, 197));
        jPanel1.setFont(new java.awt.Font("Bodoni MT Poster Compressed", 0, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        startSim.setBackground(new java.awt.Color(201, 124, 93));
        startSim.setFont(new java.awt.Font("Barlow Condensed ExtraBold", 1, 14)); // NOI18N
        startSim.setForeground(new java.awt.Color(225, 229, 197));
        startSim.setText("Iniciar Simulacion");
        startSim.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 124, 93), 5, true));
        startSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startSimActionPerformed(evt);
            }
        });
        jPanel1.add(startSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 150, 50));

        jSeparator1.setForeground(new java.awt.Color(54, 57, 59));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 10, 400));

        jSeparator2.setForeground(new java.awt.Color(54, 57, 59));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 70, 400));

        jLabel3.setFont(new java.awt.Font("Barlow Condensed Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(54, 57, 59));
        jLabel3.setText("Ganadores");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, 30));

        jLabel4.setFont(new java.awt.Font("Barlow Condensed Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(54, 57, 59));
        jLabel4.setText("Nivel 1");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, 30));

        jScrollPane4.setBorder(null);

        tier1Swars.setBackground(new java.awt.Color(230, 225, 197));
        tier1Swars.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 57, 59), 1, true));
        tier1Swars.setFont(new java.awt.Font("Barlow Condensed", 0, 12)); // NOI18N
        tier1Swars.setForeground(new java.awt.Color(54, 57, 59));
        tier1Swars.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(tier1Swars);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 150, 100));

        jScrollPane5.setBorder(null);

        tier3Nick.setBackground(new java.awt.Color(230, 225, 197));
        tier3Nick.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 57, 59), 1, true));
        tier3Nick.setFont(new java.awt.Font("Barlow Condensed", 0, 12)); // NOI18N
        tier3Nick.setForeground(new java.awt.Color(54, 57, 59));
        tier3Nick.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(tier3Nick);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 150, 100));

        jLabel5.setFont(new java.awt.Font("Barlow Condensed Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(54, 57, 59));
        jLabel5.setText("Nivel 3");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, 30));

        jLabel6.setFont(new java.awt.Font("Barlow Condensed Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(54, 57, 59));
        jLabel6.setText("Nivel 2");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, 30));

        jScrollPane8.setBorder(null);

        tier2Swars.setBackground(new java.awt.Color(230, 225, 197));
        tier2Swars.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 57, 59), 1, true));
        tier2Swars.setFont(new java.awt.Font("Barlow Condensed", 0, 12)); // NOI18N
        tier2Swars.setForeground(new java.awt.Color(54, 57, 59));
        tier2Swars.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(tier2Swars);

        jPanel1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 150, 100));

        jLabel8.setFont(new java.awt.Font("Barlow Condensed Black", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(54, 57, 59));
        jLabel8.setText("Refuerzo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, 30));

        jScrollPane9.setBorder(null);

        effortSwars.setBackground(new java.awt.Color(230, 225, 197));
        effortSwars.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 57, 59), 1, true));
        effortSwars.setFont(new java.awt.Font("Barlow Condensed", 0, 12)); // NOI18N
        effortSwars.setForeground(new java.awt.Color(54, 57, 59));
        effortSwars.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(effortSwars);

        jPanel1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 150, 100));

        jLabel7.setFont(new java.awt.Font("Barlow Condensed Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(54, 57, 59));
        jLabel7.setText("Ganadores");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, -1, 30));

        jLabel9.setFont(new java.awt.Font("Barlow Condensed Black", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(54, 57, 59));
        jLabel9.setText("Nivel 1");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, -1, 30));

        jScrollPane7.setBorder(null);

        tier1StarTrek.setBackground(new java.awt.Color(230, 225, 197));
        tier1StarTrek.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 57, 59), 1, true));
        tier1StarTrek.setFont(new java.awt.Font("Barlow Condensed", 0, 12)); // NOI18N
        tier1StarTrek.setForeground(new java.awt.Color(54, 57, 59));
        tier1StarTrek.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(tier1StarTrek);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 150, 100));

        jLabel10.setFont(new java.awt.Font("Barlow Condensed Black", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(54, 57, 59));
        jLabel10.setText("Nivel 3");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, -1, 30));

        jScrollPane10.setBorder(null);

        tier3Strek.setBackground(new java.awt.Color(230, 225, 197));
        tier3Strek.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 57, 59), 1, true));
        tier3Strek.setFont(new java.awt.Font("Barlow Condensed", 0, 12)); // NOI18N
        tier3Strek.setForeground(new java.awt.Color(54, 57, 59));
        tier3Strek.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane10.setViewportView(tier3Strek);

        jPanel1.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, 150, 100));

        jLabel11.setFont(new java.awt.Font("Barlow Condensed Black", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(54, 57, 59));
        jLabel11.setText("Nivel 2");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 270, -1, 30));

        jScrollPane11.setBorder(null);

        tier2Strek.setBackground(new java.awt.Color(230, 225, 197));
        tier2Strek.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 57, 59), 1, true));
        tier2Strek.setFont(new java.awt.Font("Barlow Condensed", 0, 12)); // NOI18N
        tier2Strek.setForeground(new java.awt.Color(54, 57, 59));
        tier2Strek.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane11.setViewportView(tier2Strek);

        jPanel1.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 300, 150, 100));

        jLabel12.setFont(new java.awt.Font("Barlow Condensed Black", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(54, 57, 59));
        jLabel12.setText("Refuerzo");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 400, -1, 30));

        jScrollPane12.setBorder(null);

        effortStrek.setBackground(new java.awt.Color(230, 225, 197));
        effortStrek.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 57, 59), 1, true));
        effortStrek.setFont(new java.awt.Font("Barlow Condensed", 0, 12)); // NOI18N
        effortStrek.setForeground(new java.awt.Color(54, 57, 59));
        effortStrek.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane12.setViewportView(effortStrek);

        jPanel1.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 430, 150, 100));

        winnersStrek.setBackground(new java.awt.Color(145, 178, 228));
        winnersStrek.setFont(new java.awt.Font("Barlow Condensed ExtraBold", 0, 48)); // NOI18N
        winnersStrek.setForeground(new java.awt.Color(230, 225, 197));
        winnersStrek.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winnersStrek.setText("0");
        winnersStrek.setOpaque(true);
        jPanel1.add(winnersStrek, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 190, 90, -1));

        IDswarsP.setFont(new java.awt.Font("Barlow Condensed", 1, 14)); // NOI18N
        IDswarsP.setForeground(new java.awt.Color(54, 57, 59));
        IDswarsP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDswarsP.setText("None");
        jPanel1.add(IDswarsP, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 40, -1));

        IDStrekP.setFont(new java.awt.Font("Barlow Condensed", 1, 14)); // NOI18N
        IDStrekP.setForeground(new java.awt.Color(54, 57, 59));
        IDStrekP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDStrekP.setText("None");
        jPanel1.add(IDStrekP, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 40, -1));

        winnersSwars.setBackground(new java.awt.Color(145, 178, 228));
        winnersSwars.setFont(new java.awt.Font("Barlow Condensed ExtraBold", 0, 48)); // NOI18N
        winnersSwars.setForeground(new java.awt.Color(230, 225, 197));
        winnersSwars.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winnersSwars.setText("0");
        winnersSwars.setOpaque(true);
        jPanel1.add(winnersSwars, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 90, -1));

        IDcartoonText.setFont(new java.awt.Font("Barlow Condensed", 1, 14)); // NOI18N
        IDcartoonText.setForeground(new java.awt.Color(54, 57, 59));
        IDcartoonText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDcartoonText.setText("ID:");
        jPanel1.add(IDcartoonText, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 40, -1));

        IDtextNick.setFont(new java.awt.Font("Barlow Condensed", 1, 14)); // NOI18N
        IDtextNick.setForeground(new java.awt.Color(54, 57, 59));
        IDtextNick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDtextNick.setText("ID:");
        jPanel1.add(IDtextNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 30, -1));

        fighterStrek.setFont(new java.awt.Font("Barlow Condensed", 1, 14)); // NOI18N
        fighterStrek.setForeground(new java.awt.Color(54, 57, 59));
        fighterStrek.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fighterStrek.setText("Nombre Strek");
        jPanel1.add(fighterStrek, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 359, 130, 30));

        jLabel16.setFont(new java.awt.Font("Barlow Condensed Black", 2, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(201, 124, 93));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("VS");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 40, -1));

        fighterSwars.setFont(new java.awt.Font("Barlow Condensed", 1, 14)); // NOI18N
        fighterSwars.setForeground(new java.awt.Color(54, 57, 59));
        fighterSwars.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fighterSwars.setText("Nombre Swars");
        jPanel1.add(fighterSwars, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 120, -1));

        stateAI.setFont(new java.awt.Font("Barlow Condensed Black", 0, 24)); // NOI18N
        stateAI.setForeground(new java.awt.Color(54, 57, 59));
        stateAI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stateAI.setText("Decidiendo");
        jPanel1.add(stateAI, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 220, -1));

        jLabel2.setFont(new java.awt.Font("Barlow Condensed ExtraBold", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(54, 57, 59));
        jLabel2.setText("Velocidad de Simulacion");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, -1, -1));

        simSpeed.setBackground(new java.awt.Color(225, 229, 197));
        simSpeed.setFont(new java.awt.Font("Barlow Condensed", 0, 12)); // NOI18N
        simSpeed.setForeground(new java.awt.Color(54, 57, 59));
        simSpeed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.25", "0.5", "1", "1.5", "2", "2.5", "3" }));
        simSpeed.setSelectedIndex(2);
        simSpeed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 57, 59)));
        simSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simSpeedActionPerformed(evt);
            }
        });
        jPanel1.add(simSpeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, 110, -1));

        strekCharacterImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        strekCharacterImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StartrekImagenes/AverageCardStrek.png"))); // NOI18N
        jPanel1.add(strekCharacterImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 110, -1));

        swarsPersonajeImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        swarsPersonajeImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StarWarsImagenes/AverageCardAvatar.png"))); // NOI18N
        jPanel1.add(swarsPersonajeImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 120, -1));

        swarsTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StarWarsImagenes/AverageCardAvatar.png"))); // NOI18N
        jPanel1.add(swarsTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 140, 220));

        StrekPersonajeCard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StrekPersonajeCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StartrekImagenes/AverageCardStrek.png"))); // NOI18N
        jPanel1.add(StrekPersonajeCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 150, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startSimActionPerformed
        Init init = new Init(this, this.buffer);
        init.init();
        this.startSim.setEnabled(false);
        
    }//GEN-LAST:event_startSimActionPerformed

    private void simSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simSpeedActionPerformed
        double newSimSpeed = Double.parseDouble(this.simSpeed.getSelectedItem().toString());
       
        this.buffer.setSimSpeed(1000/newSimSpeed);
        this.buffer.setNextSim(4000/newSimSpeed);
        this.buffer.setSimLoad(2000/newSimSpeed);
        
    }//GEN-LAST:event_simSpeedActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDStrekP;
    private javax.swing.JLabel IDcartoonText;
    private javax.swing.JLabel IDswarsP;
    private javax.swing.JLabel IDtextNick;
    private javax.swing.JLabel StrekPersonajeCard;
    private javax.swing.JList<String> effortStrek;
    private javax.swing.JList<String> effortSwars;
    private javax.swing.JLabel fighterStrek;
    private javax.swing.JLabel fighterSwars;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> simSpeed;
    private javax.swing.JButton startSim;
    private javax.swing.JLabel stateAI;
    private javax.swing.JLabel strekCharacterImage;
    private javax.swing.JLabel swarsPersonajeImagen;
    private javax.swing.JLabel swarsTarjeta;
    private javax.swing.JList<String> tier1StarTrek;
    private javax.swing.JList<String> tier1Swars;
    private javax.swing.JList<String> tier2Strek;
    private javax.swing.JList<String> tier2Swars;
    private javax.swing.JList<String> tier3Nick;
    private javax.swing.JList<String> tier3Strek;
    private javax.swing.JLabel winnersStrek;
    private javax.swing.JLabel winnersSwars;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the IDcartoon
     */
   

    /**
     * @return the StrekPersonajeCard
     */
    public javax.swing.JLabel getStrekPersonajeCard() {
        return StrekPersonajeCard;
    }

    /**
     * @param StrekPersonajeCard the StrekPersonajeCard to set
     */
    public void setStrekPersonajeCard(javax.swing.JLabel StrekPersonajeCard) {
        this.StrekPersonajeCard = StrekPersonajeCard;
    }

    /**
     * @return the strekCharacterImage
     */
    public javax.swing.JLabel getStrekPersonajeImagen() {
        return strekCharacterImage;
    }

    /**
     * @param cartoonCharacterImage the strekCharacterImage to set
     */
    public void setStrekPersonajeImagen(javax.swing.JLabel cartoonCharacterImage) {
        this.strekCharacterImage = cartoonCharacterImage;
    }

    /**
     * @return the effortStrek
     */
    public javax.swing.JList<String> getEffortStrek() {
        return effortStrek;
    }

    /**
     * @param effortCartoon the effortStrek to set
     */
    public void setEffortStrek(javax.swing.JList<String> effortCartoon) {
        this.effortStrek = effortCartoon;
    }

    /**
     * @return the effortSwars
     */
    public javax.swing.JList<String> getEffortSwars() {
        return effortSwars;
    }

    /**
     * @param effortNick the effortSwars to set
     */
    public void setEffortSwars(javax.swing.JList<String> effortNick) {
        this.effortSwars = effortNick;
    }

    /**
     * @return the fighterCartoon
     */
    public javax.swing.JLabel getFighterStrek() {
        return fighterStrek;
    }

    /**
     * @param fighterStrek the fighterStrek to set
     */
    public void setFighterStrek(javax.swing.JLabel fighterStrek) {
        this.fighterStrek = fighterStrek;
    }

    /**
     * @return the fighterNick
     */
    public javax.swing.JLabel getFighterSwars() {
        return fighterSwars;
    }

    /**
     * @param fighterSwars the fighterSwars to set
     */
    public void setFighterSwars(javax.swing.JLabel fighterSwars) {
        this.fighterSwars = fighterSwars;
    }

    /**
     * @return the jComboBox1
     */
    public javax.swing.JComboBox<String> getjComboBox1() {
        return simSpeed;
    }

    /**
     * @return the swarsTarjeta
     */
    public javax.swing.JLabel getSwarsTarjeta() {
        return swarsTarjeta;
    }

    /**
     * @param swarsTarjeta the swarsTarjeta to set
     */
    public void setSwarsTarjeta(javax.swing.JLabel swarsTarjeta) {
        this.swarsTarjeta = swarsTarjeta;
    }

    /**
     * @return the swarsPersonajeImagen
     */
    public javax.swing.JLabel getSwarsPersonajeImagen() {
        return swarsPersonajeImagen;
    }

    /**
     * @param swarsPersonajeImagen the swarsPersonajeImagen to set
     */
    public void setSwarsPersonajeImagen(javax.swing.JLabel swarsPersonajeImagen) {
        this.swarsPersonajeImagen = swarsPersonajeImagen;
    }

    /**
     * @return the stateAI
     */
    public javax.swing.JLabel getStateAI() {
        return stateAI;
    }

    /**
     * @param stateAI the stateAI to set
     */
    public void setStateAI(javax.swing.JLabel stateAI) {
        this.stateAI = stateAI;
    }

    /**
     * @return the tier1StarTrek
     */
    public javax.swing.JList<String> getTier1StarTrek() {
        return tier1StarTrek;
    }

    /**
     * @param tier1StarTrek the tier1StarTrek to set
     */
    public void setTier1StarTrek(javax.swing.JList<String> tier1StarTrek) {
        this.tier1StarTrek = tier1StarTrek;
    }

    
    public javax.swing.JList<String> getTier1Swars() {
        return tier1Swars;
    }

   
    public void setTier1Swars(javax.swing.JList<String> tier1Nick) {
        this.tier1Swars = tier1Nick;
    }

    
    public javax.swing.JList<String> getTier2Strek() {
        return tier2Strek;
    }

    
    public void setTier2Strek(javax.swing.JList<String> tier2Cartoon) {
        this.tier2Strek = tier2Cartoon;
    }

   
    public javax.swing.JList<String> getTier2Swars() {
        return tier2Swars;
    }

    
    public void setTier2Swars(javax.swing.JList<String> tier2Swars) {
        this.tier2Swars = tier2Swars;
    }

    public javax.swing.JList<String> getTier3Strek() {
        return tier3Strek;
    }

    
    public void setTier3Strek(javax.swing.JList<String> tier3Cartoon) {
        this.tier3Strek = tier3Cartoon;
    }

    
    public javax.swing.JList<String> getTier3Swars() {
        return tier3Nick;
    }

    
    public void setTier3Swars(javax.swing.JList<String> tier3Nick) {
        this.tier3Nick = tier3Nick;
    }

    
    public javax.swing.JLabel getWinnersStrek() {
        return winnersStrek;
    }

    
    public void setWinnersStrek(javax.swing.JLabel winnersCartoon) {
        this.winnersStrek = winnersCartoon;
    }

    /**
     * @return the winnersSwars
     */
    public javax.swing.JLabel getWinnersSwars() {
        return winnersSwars;
    }

    /**
     * @param winnersNick the winnersSwars to set
     */
    public void setWinnersSwars(javax.swing.JLabel winnersNick) {
        this.winnersSwars = winnersNick;
    }

    /**
     * @return the IDswarsP
     */
    public javax.swing.JLabel getIDSwarsP() {
        return IDswarsP;
    }

    /**
     * @return the IDStrekP
     */
    public javax.swing.JLabel getIDStrekP() {
        return IDStrekP;
    }
}
